### ISSUE TITLE
Condition bug

### ISSUE THREAD

**Issue by Tigerwraith** [BattleScribe/Release#102] opened 2019-11-20 21:23 UTC
I'm having an issue with a Shared Selection Entry group not hiding when I set a condition if primary Catalogue instance of Death - Ossiarch Bonereapers. This worked in 2.03.01, but it has not worked in .06, .07, or .08 the newest release. 
![ssegerror](https://user-images.githubusercontent.com/39889736/69279254-95461c80-0ba9-11ea-9367-1677b21894a1.PNG) this pic shows the issue in .08

![ssegerror1](https://user-images.githubusercontent.com/39889736/69279312-b3ac1800-0ba9-11ea-9af1-1b38b9495a02.PNG)
This one shows it working in .01

**Comment by Jonskichov** [comment] 2019-11-21 17:09
This is a duplicate of https://github.com/BattleScribe/Release/issues/94

It's fixed for the next version 👍

**Closed as completed by Jonskichov** 2019-11-21 17:09 UTC
