### ISSUE TITLE
Shared selection entry constraint stopped working.

### ISSUE THREAD

**Issue by L3610N115** [BattleScribe/Release#111] opened 2019-12-29 16:01 UTC
The following constraint used to work in v.2.03.10 and stopped working in v. 2.03.11.

![grafik](https://user-images.githubusercontent.com/47950292/71559274-736b6f80-2a5c-11ea-85c6-a5110de32e03.png)

Screenshot of v.2.03.10
https://cdn.discordapp.com/attachments/550296225044234240/651896849073963018/unknown.png

Screenshot of v.2.03.11
https://cdn.discordapp.com/attachments/570596379991343138/660868989148200971/unknown.png

**Comment by amis92** [comment] 2019-12-29 18:20
Duplicate of https://github.com/BattleScribe/Release/issues/107

**Comment by Jonskichov** [comment] 2020-02-20 19:27
Fixed: https://github.com/BattleScribe/Release/issues/107

**Closed as completed by Jonskichov** 2020-02-20 19:27 UTC
