### ISSUE TITLE
Feature Request: Make Tab work again to move between fields

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#168] opened 2020-04-24 09:18 UTC
Looks like text fields in the new framework support tabbing, so it's no longer possible to tab between fields; you just end up entering tabs into the text field.

Hopefully this behaviour can be changed?

**Comment by Mad-Spy** [comment] 2020-04-24 10:27
Ok, looks like it's just moved to being CTRL-Tab instead. My muscle memory is wasted!

**Comment by Jonskichov** [comment] 2020-04-27 13:41
Not intended behaviour, I'll take a look

**Comment by Jonskichov** [comment] 2020-04-28 18:33
Working OK with me using TAB...

Is this happening everywhere or on certain panels?

What system are you on? Win/Mac/Linux (lol)

**Comment by Jonskichov** [comment] 2020-05-02 03:38
Fixed in 2.03.18.157

**Closed as completed by Jonskichov** 2020-05-02 03:38 UTC
Labels: Bug, Desktop, Editor, Done
